### ISSUE TITLE
[18] [REFACTOR] 화면 전환시 Data의 유지를 위해 MainViewModel을 Singleton으로 하는 것 외에 방법 찾기

### ISSUE THREAD

**Issue by kwangddang** [woowa-techcamp-2022/android-repo-04#49]

**Comment by rosf73** [comment]
그냥 이 부분을 개발할 때 했던 생각을 공유해드립니다!

제가 처음에 이 부분 개발할 때 두 가지 중에 고민하긴 했습니다.
- `MainActivity`에서 API를 요청한 뒤 각 프래그먼트에게 `Bundle` 전송
- 현재 방법인 Singleton 개발

첫 번째의 단점은, 값이 변경될 때 마다 Bundle을 전송해야하기 때문에 스크롤 상태가 유지되지 않는다는 점이었습니다.
그래서 별 다른 고민없이 두 번째로 결정하였습니다.

**Comment by rosf73** [comment]
혹시 ViewModel이 Singleton일 때 생기는 문제로 어떤걸 떠올리셨는지 알수있을까요?!

**Comment by rosf73** [comment]
앗 아니면 CustomViewModelFactory에서 이미 생성된 멤버 객체를 반환해주는 방식을 이용하면 어떨까요?

**Comment by kwangddang** [comment]
MainViewModel이 싱글턴으로 유지되어야 하는 이유가 어떤 건지 혹시 설명해주실 수 있나요??

**Comment by rosf73** [comment]
IssueFragment, NotificationFragment, MainFragment 가 동일한 인스턴스를 조회해야하기 때문입니다!

**Comment by rosf73** [comment]
근데 livedata가 레퍼런스를 조회하는 거면 굳이 그러지 않아도 동일한 인스턴스를 조회할지도 모르겠네요..
한번 테스트 해봐야 알것같습니다!
debounce 이후에 한번 테스트 해볼게요

**Comment by kwangddang** [comment]
화면이 전환될 때 ViewModel은 소멸되지 않고 그대로 유지되니 MainViewModel은 재생성 되지 않습니다.
그리고 Issue와 Notifcation Fragment는 MainViewModel을 이용하게 되는데
이때, MainViewModel을 재생성하는 것이 아닌 MainActivity에 있는 ViewModel을 공유 받으면
싱글톤으로 하지 않아도 모두 동일한 인스턴스를 조회할 수 있습니다..!

https://velog.io/@cherish307/Why-should-ViewModel-not-be-Singleton-Object
1. (싱글턴으로 구현 시) 오브젝트 특성상, Database로부터 어떤 데이터를 갖고올 필요가 없는 상황에서도 계속 데이터베이스 참조를 유지함 = 메모리 누수로 이어짐
2. 여러 곳에서 참조하기 때문에 유닛 테스트가 어려워짐

위 블로그와 스택오버플로우에서는 ViewModel을 싱글톤으로 만드는 것을 권장하지 않는 것 같습니다!

**Comment by kwangddang** [comment]
제가 지금 구현해봤는데 싱글톤으로 하지 않아도 잘 되는 것 같아요 ㅎㅎ
완성하고 PR 날려보겠습니다!

**Comment by rosf73** [comment]
아 ViewModel을 공유받는다는 생각은 하지 못했네요.. 저는 ViewModel은 싱글톤으로 존재해야한다는 글을 봤었습니다. 공식 문서에서는 여러 View에서 동일한 LiveData를 조회할 때 LiveData를 싱글톤으로 구현하라고 하네요..!
[https://developer.android.com/topic/libraries/architecture/livedata#extend_livedata](https://developer.android.com/topic/libraries/architecture/livedata#extend_livedata)

> The fact that LiveData objects are lifecycle-aware means that you can share them between multiple activities, fragments, and services. To keep the example simple, you can implement the LiveData class as a singleton as follows:

**Comment by kwangddang** [comment]
아하 LiveData를 싱글톤으로 구현하는 경우도 있군요
처음 알았습니다! 좋은 정보 감사합니다 :)
